### ISSUE TITLE
module error when installing plugin from zip

### ISSUE THREAD

**Issue by hmcgrath** [NRCan/CanCurve#28]
Disregard - I've downloaded from DEV and see that's the branch I should be testing. 

downloaded today (11/7/2024) upon install to : QGIS 3.34.5
Get the warning of missing module. 
Plugin does say it's successfully installed. 
* this is from the MAIN.. am I to be testing from dev branch? 

warning: 
_```
Couldn't load plugin 'cancurve/dev_test_data/case4_R2' 

ModuleNotFoundError: No module named 'cancurve/dev_test_data/case4_R2' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'cancurve/dev_test_data/case4_R2'

Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS version: 3.34.5-Prizren Prizren, 4b308492 

Python Path:
C:\Users/hmcgrath/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\whitebox_workflows_for_qgis
C:\Users/hmcgrath/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:/PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python
C:/Users/hmcgrath/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/hmcgrath/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.5\apps\grass\grass83\etc\python
C:\Users\hmcgrath\Documents
C:\Program Files\QGIS 3.34.5\bin\python39.zip
C:\PROGRA~1\QGIS33~1.5\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib
C:\Program Files\QGIS 3.34.5\bin
C:\PROGRA~1\QGIS33~1.5\apps\Python39
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\Pythonwin
C:/Users/hmcgrath/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\hmcgrath\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\canflood
```_

**Comment by hmcgrath** [comment]
should have been looking at dev branch.
